import "./globals.css";
import Navigation from "./components/Navigation";
import { Inter } from "next/font/google";
import { DataProvider } from "./DataProvider";

const inter = Inter({ subsets: ["latin"], weights: ["400", "700", "800"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* Data provided through context API */}
        <DataProvider>
          <Navigation />
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
